spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false

  datasource:
    url: jdbc:mysql://localhost:3306/mysql_db
    username: lian
    password: osclablian!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
      format_sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: false
      show-sql: true

server:
  port: 8080